name: Packer AMI Build

on:
  pull_request:
    types: [closed]

jobs:
  packer-ami-build:
    name: Packer AMI Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2.0.0

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp1.zip .

      # - name: Set up AWS credentials
      #   run: |
      #     mkdir -p ~/.aws
      #     echo -e "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Packer build
        run: |
          cd ./packer
          packer init .
          packer build ./ami.pkr.hcl
          packer build -var "aws_region=${AWS_REGION}" -var "source_ami=${SOURCE_AMI}" -var "ssh_username=${SSH_USERNAME}" -var "subnet_id=${SUBNET_ID}" ./ami.pkr.hcl
