name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SOURCE_AMI: ${{ secrets.SOURCE_AMI }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SUBNET_ID: ${{ secrets.SUBNET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2.0.0

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo -e "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: configuration
        run: touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DB=${{ secrets.DATABASE }} >> .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo DIALECT=${{ secrets.DIALECT }} >> .env
          echo USER=${{ secrets.USER }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      - name: Build zip
        working-directory: ${{ github.workspace }}
        run: zip -r webapp1.zip .

      - name: Run Packer fmt
        run: |
          cd ./packer
          packer init .
          if ! packer fmt -check ./ami.pkr.hcl; then
           echo "Packer format check failed"
           exit 1
          fi

          if ! packer validate ./ami.pkr.hcl; then
            echo "Packer validate failed"
            exit 1
          fi
