name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-checks:
    name: Packer Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2.0.0

      - name: Run Packer fmt
        run: |
          packer fmt ./packer/ami.pkr.hcl

      - name: Run Packer validate
        run: |
          packer validate ./packer/ami.pkr.hcl
