name: Webapp

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: "cloud_db"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Node.js project
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Wait for MySQL to be ready
        run: |
          until nc -z -v -w30 localhost 3306
          do
            echo "Waiting for MySQL to be ready..."

            sleep 5
          done
      # - name: Grant MySQL Access
      #   run: |
      #     mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON cloud_db.* TO 'keerthana'@'%' IDENTIFIED BY 'Karan@123'; FLUSH PRIVILEGES;"

      - name: Install project dependencies
        run: npm install

      - name: Run Integration tests
        run:
          #   DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          #   DB_USER: keerthana
          #   DB_PORT: 33306
          #   DB_HOST: localhost
          # run:
          #   mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON cloud_db.* TO 'keerthana'@'%' IDENTIFIED BY 'Karan@123'; FLUSH PRIVILEGES;"
          npm test
