name: Webapp

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "Karan@123"
          MYSQL_DATABASE: "cloud_db"
          PASSWORD: "Karan@123"
          HOST: "127.0.0.1"
          USER: "root"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Node.js project
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm i

      - name: Run Integration tests
        run: npm test
        env:
          HOST: "127.0.0.1"
          PASSWORD: "Karan@123"
          USER: "root"
          DB: "cloud_db"
