name: Webapp

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          PASSWORD: "Karan@123"
          DB: "cloud_db"
          HOST: "172.18.0.1"
          USER: "root"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Configuration
      #   run: |
      #     touch .env
      #     echo PORT=${{ secrets.PORT }} >> .env
      #     echo DB=${{ secrets.DATABASE }} >> .env
      #     echo HOST= 172.18.0.1 >> .env
      #     echo DIALECT=${{ secrets.DIALECT }} >> .env
      #     echo USER= root >> .env
      #     echo PASSWORD=${{ secrets.PASSWORD }} >> .env

      - name: Run Node.js project
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm i

      - name: Run Integration tests
        run: npm test
